#!/usr/bin/env bash
# A Bash script that stops the 4-to_infinity_and_beyond process

# Find the PID of the script and kill it
pid=$(pgrep -f 4-to_infinity_and_beyond)

# Check if PID exists before trying to kill it
if [ -n "$pid" ]; then
  kill "$pid"
fi
